#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"helloworld": "00_core.ipynb",
         "helloworld2": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/remcovdh/nbdev_test/tree/master/"

def custom_doc_links(name): return None