#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['helloworld', 'helloworld2']

#Cell
def helloworld(a):
    print('Hello world '+ a)

#Cell
def helloworld2(a):
    print('Hello world two '+ a)